// Generated by CoffeeScript 1.10.0
(function() {
  mw.Cell = (function() {
    function Cell(x, y) {
      this.x = x;
      this.y = y;
      this.terrain = new mw.Terrain(this.x, this.y);
    }

    return Cell;

  })();

}).call(this);
