// Generated by CoffeeScript 1.9.1
(function() {
  mw.Cell = (function() {
    function Cell(x, y) {
      this.x = x;
      this.y = y;
      console.log("new cell " + this.x + ", " + this.y);
      this.terrain = new mw.Terrain(this.x, this.y);
    }

    return Cell;

  })();

}).call(this);
