// Generated by CoffeeScript 1.10.0
(function() {
  var clock, onDocumentMouseMove, onWindowResize, render, windowHalfX, windowHalfY;

  mw.mouseX = 0;

  mw.mouseY = 0;

  windowHalfX = window.innerWidth / 2;

  windowHalfY = window.innerHeight / 2;

  mw.boot = function() {
    var container, span, wisp;
    container = document.createElement('div');
    document.body.appendChild(container);
    this.camera = new THREE.PerspectiveCamera(45, window.innerWidth / window.innerHeight, 20, 50000);
    this.camera.position.set(-13088.357563362384, -70417.86172521245, 675.7888756651994);
    this.camera.up = new THREE.Vector3(0, 0, 1);
    this.controls = new THREE.FirstPersonControls(this.camera);
    this.controls.movementSpeed = 1000;
    this.controls.lookSpeed = 0.25;
    this.scene = new THREE.Scene;
    this.scene.fog = new THREE.Fog(mw.Fog, 2250, 9000);
    this.scene.add(new THREE.AmbientLight(mw.Ambient));
    this.sun = new THREE.DirectionalLight(mw.Sun, 1);
    this.sun.name = 'Sun ^^';
    this.sun.position.set(-9736.193505934018, -71181.47477616863, 1385.0809414861014);
    this.sun.target.position.set(-11224, -70869, 300);
    this.sun.castShadow = true;
    this.sun.shadow.darkness = 5;
    span = 1500;
    this.sun.shadow.camera.near = 5;
    this.sun.shadow.camera.far = 6000;
    this.sun.shadow.camera.right = span;
    this.sun.shadow.camera.left = -span;
    this.sun.shadow.camera.top = span;
    this.sun.shadow.camera.bottom = -span;
    this.sun.shadow.mapSize.width = 2048;
    this.sun.shadow.mapSize.height = 2048;
    this.scene.add(this.sun);
    this.scene.add(this.sun.target);
    wisp = new THREE.PointLight(0xf58c28, 1, 100);
    wisp.position.set(-11738.976, -70195.289, 385.415);
    this.scene.add(wisp);
    THREE.Loader.Handlers.add(/\.dds$/i, new THREE.DDSLoader);
    this.renderer = new THREE.WebGLRenderer({
      antialias: true
    });
    this.maxAnisotropy = this.renderer.getMaxAnisotropy();
    this.renderer.setPixelRatio(window.devicePixelRatio);
    this.renderer.setSize(window.innerWidth, window.innerHeight);
    this.renderer.shadowMap.enabled = true;
    this.renderer.shadowMap.type = THREE.PCFShadowMap;
    this.stats = new Stats();
    this.stats.domElement.style.position = 'absolute';
    this.stats.domElement.style.top = '0px';
    container.appendChild(this.stats.domElement);
    container.appendChild(this.renderer.domElement);
    document.addEventListener('mousemove', onDocumentMouseMove, false);
    window.addEventListener('resize', onWindowResize, false);
    this.clock = new THREE.Clock();
    return true;
  };

  ({
    audios: function() {
      var loader;
      return loader = new THREE.SEA3D({
        autoPlay: true,
        container: scene
      });
    }
  });

  onWindowResize = function() {
    windowHalfX = window.innerWidth / 2;
    windowHalfY = window.innerHeight / 2;
    mw.camera.aspect = window.innerWidth / window.innerHeight;
    mw.camera.updateProjectionMatrix();
    mw.renderer.setSize(window.innerWidth, window.innerHeight);
  };

  onDocumentMouseMove = function(event) {
    mw.mouseX = (event.clientX - windowHalfX) * 2;
    mw.mouseY = (event.clientY - windowHalfY) * 2;
  };

  mw.animate = function() {
    var i, j, k, len, ref;
    requestAnimationFrame(mw.animate);
    mw.delta = mw.clock.getDelta();
    if (!mw.freeze) {
      mw.controls.update(mw.delta);
    }
    if (mw.keys[77] === 1) {
      mw.freeze = !mw.freeze;
    }
    if (mw.keys[20] === 1) {
      mw.slow = !mw.slow;
      if (mw.slow) {
        mw.controls.movementSpeed = 200;
        mw.controls.lookSpeed = 0.15;
      } else {
        mw.controls.movementSpeed = 1000;
        mw.controls.lookSpeed = 0.25;
      }
    }
    if (mw.keys[72] === 1) {

    }
    if (mw.world) {
      mw.world.step();
    }
    if (mw.water) {
      mw.water.material.uniforms.time.value += 1.0 / 60.0;
    }
    render.call(mw);
    mw.stats.update();
    ref = mw.keys;
    for (i = j = 0, len = ref.length; j < len; i = ++j) {
      k = ref[i];
      if (k) {
        mw.keys[i] = 2;
      }
    }
  };

  clock = new THREE.Clock();

  render = function() {
    var angle, x, y, z;
    angle = Date.now() / 200 * Math.PI;
    x = -11576.443208275043 - -9736.193505934018;
    y = -70815.55892959078 - -71181.47477616863;
    z = 381.1055788146208 - 1385.0809414861014;
    mw.sun.position.set(mw.camera.position.x - x, mw.camera.position.y - y, mw.camera.position.z - z);
    x = -11224 - -9736.193505934018;
    y = -70869 - -71181.47477616863;
    z = 300 - 1385.0809414861014;
    mw.sun.target.position.set(mw.sun.position.x + x, mw.sun.position.y + y, mw.sun.position.z + z);
    if (mw.water) {
      mw.water.render();
    }
    THREE.AnimationHandler.update(clock.getDelta());
    this.renderer.render(this.scene, this.camera);
  };

}).call(this);
