// Generated by CoffeeScript 1.9.1
(function() {
  var mw, root;

  root = typeof exports !== "undefined" && exports !== null ? exports : this;

  mw = root.mw = {
    world: null
  };

  $(document).ready(function() {
    var loader;
    $.ajaxSetup({
      'async': false
    });
    mw.boot.call(mw);
    loader = new THREE.OBJMTLLoader;
    return loader.load('models/male02.obj', 'models/male02_dds.mtl', function(object) {
      object.position.y = -80;
      mw.scene.add(object);
      return true;
    });
  });

}).call(this);
