// Generated by CoffeeScript 1.10.0
(function() {
  mw.Player = (function() {
    function Player(x, y) {
      this.x = x;
      this.y = y;
    }

    Player.prototype["do"] = 0;

    return Player;

  })();

}).call(this);
