// Generated by CoffeeScript 1.10.0
(function() {
  mw.Prop = (function() {
    function Prop(data) {
      var d;
      this.data = data;
      d = this.data;
      this.type = 'Prop';
      this.x = d.x;
      this.y = d.y;
      this.z = d.z;
      this.r = Math.abs(d.r - 360);
      this.r *= mw.DEGTORAD;
      this.mesh = null;
      this.shape();
      this.pose();
      this.mesh.updateMatrix();
      this.mesh.updateMatrixWorld();
      this.mesh.matrixAutoUpdate = false;
      if (this.mesh != null) {
        mw.scene.add(this.mesh);
      }
    }

    Prop.prototype.shape = function() {
      this.model = this.data.model;
      if (!((mw.models[this.model] != null) && mw.models[this.model] !== -1)) {
        return;
      }
      this.mesh = mw.models[this.model].scene.clone();
      this.mesh.name = 'Prop';
      if (this.data.scale) {
        this.mesh.scale.set(this.scale, this.scale, this.scale);
      }
      return 0;
    };

    Prop.prototype.pose = function() {
      this.mesh.position.set(this.x, this.y, this.z);
      this.mesh.rotation.z = this.r;
      return 0;
    };

    Prop.prototype.step = function() {
      return true;
    };

    return Prop;

  })();

}).call(this);
