// Generated by CoffeeScript 1.10.0
(function() {
  mw.Prop = (function() {
    function Prop(data1) {
      var data;
      this.data = data1;
      data = this.data;
      this.type = 'Prop';
      this.model = data.model;
      this.x = data.x;
      this.y = data.y;
      this.z = data.z;
      this.r = Math.abs(data.r - 360);
      this.r *= mw.DEGTORAD;
      this.scale = data.scale || 0;
      this.transparent = data.transparent || false;
      this.mesh = null;
      this.shape();
      this.pose();
      if (this.mesh != null) {
        mw.scene.add(this.mesh);
      }
    }

    Prop.prototype.shape = function() {
      if (!((mw.models[this.model] != null) && mw.models[this.model] !== -1)) {
        return;
      }
      this.mesh = mw.models[this.model].scene.clone();
      if (this.scale) {
        this.mesh.scale.set(this.scale, this.scale, this.scale);
      }
      return 0;
    };

    Prop.prototype.pose = function() {
      this.mesh.position.set(this.x, this.y, this.z);
      this.mesh.rotation.z = this.r;
      return 0;
    };

    Prop.prototype.step = function() {
      return true;
    };

    return Prop;

  })();

}).call(this);
