// Generated by CoffeeScript 1.10.0
(function() {
  mw.Sound = (function() {
    function Sound(yea) {}

    Sound.prototype.step = function() {
      return true;
    };

    return Sound;

  })();

}).call(this);
