// Generated by CoffeeScript 1.10.0
(function() {
  mw.Sound = (function() {
    function Sound(raw) {
      this.raw = raw;
    }

    Sound.prototype.step = function() {
      return true;
    };

    return Sound;

  })();

}).call(this);
