// Generated by CoffeeScript 1.9.1
(function() {
  mw.Terrain = (function() {
    function Terrain(x1, y1) {
      var b, g, h, i, j, mx, my, p, px, py, r, ref, x, y;
      this.x = x1;
      this.y = y1;
      this.data = this.heights();
      this.geometry = new THREE.PlaneGeometry(4096 * 2, 4096 * 2, 64, 64);
      this.mx = mx = (this.x * 8192) + 4096;
      this.my = my = (this.y * 8192) + 4096;
      for (i = j = 0, ref = this.geometry.vertices.length - 1; 0 <= ref ? j <= ref : j >= ref; i = 0 <= ref ? ++j : --j) {
        x = this.geometry.vertices[i].x;
        y = this.geometry.vertices[i].y;
        px = (4096 + x) / 64;
        px /= 2;
        py = (4096 + y) / 64;
        py /= 2;
        p = ((py * 65) + px) * 4;
        r = this.data[p];
        g = this.data[p + 1];
        b = this.data[p + 2];
        if (r === 255) {
          this.geometry.vertices[i].z = h;
          h = -(255 - b) + (255 * ((g - 255) / 8));
        } else if (g) {
          h = (255 * (g / 8)) + b;
        } else {
          h = b;
        }
        this.geometry.vertices[i].z = h;
      }
      this.mkground();
      true;
    }

    Terrain.prototype.mkground = function() {
      this.ground = new THREE.Mesh(this.geometry, new THREE.MeshLambertMaterial({
        map: this.vclr
      }));
      this.ground.position.set(this.mx, this.my, 0);
      return mw.scene.add(this.ground);
    };

    Terrain.prototype.heights = function() {
      var canvas, context, imgd, x, y;
      this.canvas = canvas = document.createElement('canvas');
      document.body.appendChild(canvas);
      if (this.x === -2 && this.y === -9) {
        console.log('there');
        $('canvas').css('position', 'absolute');
      }
      canvas.width = 65;
      canvas.height = 65;
      context = canvas.getContext('2d');
      context.save();
      context.translate(0, 65);
      context.scale(1, -1);
      x = -(18 + this.x) * 64;
      y = -(27 - this.y) * 64;
      context.drawImage(mw.vvardenfell, x, y);
      context.getImageData(0, 0, 65, 65);
      imgd = context.getImageData(0, 0, 65, 65);
      context.drawImage(mw.vclr, x, y);
      this.vclr = new THREE.Texture(this.canvas);
      this.vclr.needsUpdate = true;
      this.vclr.magFilter = THREE.NearestFilter;
      this.vclr.minFilter = THREE.LinearMipMapLinearFilter;
      return imgd.data;
    };

    return Terrain;

  })();

  mw.splat = function() {
    var noiseTexture, waterTexture;
    noiseTexture = new THREE.ImageUtils.loadTexture('cloud.png');
    noiseTexture.wrapS = noiseTexture.wrapT = THREE.RepeatWrapping;
    noiseTexture.repeat.set(64, 64);
    waterTexture = new THREE.ImageUtils.loadTexture('water.jpg');
    waterTexture.wrapS = waterTexture.wrapT = THREE.RepeatWrapping;
    noiseTexture.repeat.set(64, 64);
    this.splatMaterial = new THREE.ShaderMaterial({
      uniforms: {
        oceanTexture: {
          type: "t",
          value: waterTexture
        },
        sandyTexture: {
          type: "t",
          value: noiseTexture
        }
      },
      vertexShader: document.getElementById('splatVertexShader').textContent,
      fragmentShader: document.getElementById('splatFragmentShader').textContent,
      transparent: true
    });
    return true;
  };

}).call(this);
