// Generated by CoffeeScript 1.10.0
(function() {
  mw.UI = (function() {
    function UI() {}

    return UI;

  })();

  mw.Window = (function() {
    function Window() {}

    return Window;

  })();

}).call(this);
