// Generated by CoffeeScript 1.10.0
(function() {
  mw.watershed = function() {
    var aMeshMirror, geometry, x, y;
    geometry = new THREE.PlaneGeometry(8192 * 3, 8192 * 3);
    x = (mw.world.x * 8192) + 4096;
    y = (mw.world.y * 8192) + 4096;
    this.waterNormals = new THREE.TextureLoader().load('textures/waternormals.jpg');
    this.waterNormals.wrapS = this.waterNormals.wrapT = THREE.RepeatWrapping;
    this.water = new THREE.Water(mw.renderer, mw.camera, mw.scene, {
      textureWidth: 512,
      textureHeight: 512,
      waterNormals: this.waterNormals,
      alpha: 1.0,
      sunColor: 0xffffff,
      waterColor: 0x001e0f,
      distortionScale: 50.0,
      opacity: .5,
      transparent: true
    });
    aMeshMirror = new THREE.Mesh(geometry, this.water.material);
    aMeshMirror.position.set(x, y, 0.5);
    aMeshMirror.add(this.water);
    mw.scene.add(aMeshMirror);
    return true;
  };

}).call(this);
