// Generated by CoffeeScript 1.9.1
(function() {
  mw.World = (function() {
    function World(data) {
      var i, len, p, ref;
      this.data = data;
      console.log('new world');
      this.props = [];
      this.cached = 0;
      ref = this.data;
      for (i = 0, len = ref.length; i < len; i++) {
        p = ref[i];
        this.cache(p.model);
      }
    }

    World.prototype.cachcb = function() {
      this.cached++;
      if (this.cached >= this.data.length) {
        this.ransack();
      }
      return true;
    };

    World.prototype.ransack = function() {
      var i, len, p, ref;
      ref = this.data;
      for (i = 0, len = ref.length; i < len; i++) {
        p = ref[i];
        this.props.push(new mw.Prop(p));
      }
      return true;
    };

    World.prototype.cache = function(model) {
      var cb, loader;
      cb = function(object) {
        mw.models[model] = object;
        console.log("put " + model);
        return mw.world.cachcb();
      };
      loader = new THREE.OBJMTLLoader;
      loader.load("models/" + model + ".obj", "models/" + model + ".mtl", cb);
      return true;
    };

    World.prototype.fuckoff = function() {
      return true;
    };

    return World;

  })();

}).call(this);
